puts "Cleaning database..."
Hobby.delete_all
User.delete_all
puts "OK"

puts "Adding Users..."
john = User.create(name: 'John Doe' , document: '123' , sex: 'M', age: '29', height: '1.80 m')
dylan = User.create(name: 'Dylan Doe' , document: '456' , sex: 'M', age: '25', height: '1.83 m')
mike = User.create(name: 'Mike Doe' , document: '789' , sex: 'M', age: '33', height: '1.75 m')
misha = User.create(name: 'Misha Doe' , document: '147' , sex: 'F', age: '27', height: '1.65 m')
haruki = User.create(name: 'Haruki Doe' , document: '258' , sex: 'F', age: '21', height: '1.63 m')
puts "OK"

puts "Adding Hobbies to Users..."
john.hobbies.create(name: 'Reading books')
john.hobbies.create(name: 'Blogging')
john.hobbies.create(name: 'Dancing')
john.hobbies.create(name: 'Singing')
john.hobbies.create(name: 'Listening to music')
john.hobbies.create(name: 'Playing musical instruments')
john.hobbies.create(name: 'Learning new languages')
dylan.hobbies.create(name: 'Shopping')
dylan.hobbies.create(name: 'Traveling')
dylan.hobbies.create(name: 'Hiking')
dylan.hobbies.create(name: 'Cycling')
dylan.hobbies.create(name: 'Exercising')
dylan.hobbies.create(name: 'Drawing')
mike.hobbies.create(name: 'Painting')
mike.hobbies.create(name: 'Collecting things')
mike.hobbies.create(name: 'Playing computer games')
mike.hobbies.create(name: 'Cooking')
mike.hobbies.create(name: 'Baking')
mike.hobbies.create(name: 'Gardening')
mike.hobbies.create(name: 'Doing crafts')
mike.hobbies.create(name: 'Embroidering')
mike.hobbies.create(name: 'Sewing')
mike.hobbies.create(name: 'Knitting')
misha.hobbies.create(name: 'Playing board games')
misha.hobbies.create(name: 'Walking')
misha.hobbies.create(name: 'Writing stories')
misha.hobbies.create(name: 'Fishing')
misha.hobbies.create(name: 'Photography')
misha.hobbies.create(name: 'Skydiving')
haruki.hobbies.create(name: 'Skating')
haruki.hobbies.create(name: 'Skiing')
haruki.hobbies.create(name: 'Roller skating')
haruki.hobbies.create(name: 'Longboarding')
haruki.hobbies.create(name: 'Surfing')
puts "OK"

put "Adding Books to Users..."
books.create(title: "Things Fall Apart", author: "Chinua Achebe", language: "English", pages: 209, year: 1958)
books.create(title: "Fairy tales", author: "Hans Christian Andersen", language: "Danish", pages: 784, year: 1836)
books.create(title: "The Divine Comedy", author: "Dante Alighieri", language: "Italian", pages: 928, year: 1315)
books.create(title: "The Epic Of Gilgamesh", author: "Unknown", language: "Akkadian", pages: 160, year: -1700)
books.create(title: "The Book Of Job", author: "Unknown", language: "Hebrew", pages: 176, year: -600)
books.create(title: "One Thousand and One Nights", author: "Unknown", language: "Arabic", pages: 288, year: 1200)
books.create(title: "Nj\u00e1l's Saga", author: "Unknown", language: "Old Norse", pages: 384, year: 1350)
books.create(title: "Pride and Prejudice", author: "Jane Austen", language: "English", pages: 226, year: 1813)
books.create(title: "Le P\u00e8re Goriot", author: "Honor\u00e9 de Balzac", language: "French", pages: 443, year: 1835)
books.create(title: "Molloy, Malone Dies, The Unnamable, the trilogy", author: "Samuel Beckett", language: "French, English", pages: 256, year: 1952)
books.create(title: "The Decameron", author: "Giovanni Boccaccio", language: "Italian", pages: 1024, year: 1351)
books.create(title: "Ficciones", author: "Jorge Luis Borges", language: "Spanish", pages: 224, year: 1965)
books.create(title: "Wuthering Heights", author: "Emily Bront\u00eb", language: "English", pages: 342, year: 1847)
books.create(title: "The Stranger", author: "Albert Camus", language: "French", pages: 185, year: 1942)
books.create(title: "Poems", author: "Paul Celan", language: "German", pages: 320, year: 1952)
books.create(title: "Journey to the End of the Night", author: "Louis-Ferdinand C\u00e9line", language: "French", pages: 505, year: 1932)
books.create(title: "Don Quijote De La Mancha", author: "Miguel de Cervantes", language: "Spanish", pages: 1056, year: 1610)
books.create(title: "The Canterbury Tales", author: "Geoffrey Chaucer", language: "English", pages: 544, year: 1450)
books.create(title: "Stories", author: "Anton Chekhov", language: "Russian", pages: 194, year: 1886)
books.create(title: "Nostromo", author: "Joseph Conrad", language: "English", pages: 320, year: 1904)
books.create(title: "Great Expectations", author: "Charles Dickens", language: "English", pages: 194, year: 1861)
books.create(title: "Jacques the Fatalist", author: "Denis Diderot", language: "French", pages: 596, year: 1796)
books.create(title: "Berlin Alexanderplatz", author: "Alfred D\u00f6blin", language: "German", pages: 600, year: 1929)
books.create(title: "Crime and Punishment", author: "Fyodor Dostoevsky", language: "Russian", pages: 551, year: 1866)
books.create(title: "The Idiot", author: "Fyodor Dostoevsky", language: "Russian", pages: 656, year: 1869)
books.create(title: "The Possessed", author: "Fyodor Dostoevsky", language: "Russian", pages: 768, year: 1872)
books.create(title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", language: "Russian", pages: 824, year: 1880)
books.create(title: "Middlemarch", author: "George Eliot", language: "English", pages: 800, year: 1871)
books.create(title: "Invisible Man", author: "Ralph Ellison", language: "English", pages: 581, year: 1952)
books.create(title: "Medea", author: "Euripides", language: "Greek", pages: 104, year: -431)
books.create(title: "Absalom, Absalom!" author: "William Faulkner", language: "English", pages: 313, year: 1936)
puts "OK"

puts "seed completed :)"